# Generated by Django 4.0.4 on 2022-05-20 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=50)),
                ('customer_phone', models.CharField(max_length=11)),
                ('number_of_people', models.IntegerField(default=1)),
                ('hotel_name', models.CharField(max_length=50)),
                ('res_date', models.DateField()),
                ('trip_date', models.DateField()),
                ('achieved_money', models.IntegerField()),
                ('rest_of_money', models.IntegerField()),
            ],
        ),
    ]
